Ini scanner mode
laminas/laminas-config pull request #10
Opened 2020-09-08 23:53 UTC by jcsanyi

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | yes

### Description
Adds a `typedMode` flag to the INI Reader to support the built-in `INI_SCANNER_TYPED` flag on `parse_ini_file()`.
This allows integer, boolean, and null values to be returned as the appropriate types, rather than all being returned as strings.

2020-09-09 09:06 UTC, Ocramius requested changes
Minor changes needed, bit otherwise seems OK.

My biggest issue with the patch is that, in order to follow consistency with pre-existing code, setters/getters are used to enable this behaviour, instead of relying on the `Reader\Ini` constructor.

2020-09-09 09:06 UTC, Ocramius commented on src/Reader/Ini.php
> +    public function setTypedMode($typedMode)
This should just accept `bool` as an input (no cast in method)

2020-09-09 09:06 UTC, Ocramius commented on src/Reader/Ini.php
> +    public function setTypedMode($typedMode)
Return type is to be specified

2020-09-09 09:06 UTC, Ocramius commented on src/Reader/Ini.php
> +    public function getTypedMode()
Return type to be specified

2020-09-09 09:06 UTC, Ocramius commented on src/Reader/Ini.php
> +    public function getScannerMode()
Return type to be specified

2020-09-10 01:25 UTC, jcsanyi commented
I added the type hinting you requested.

>My biggest issue with the patch is that, in order to follow consistency with pre-existing code, setters/getters are used to enable this behaviour, instead of relying on the Reader\Ini constructor.

I agree - I was thinking I should add constructor support for all 3 options as a follow-up PR.

2021-02-11 15:06 UTC, merged